<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

?>
<?php if (($_products = $block->getProductCollection()) && $_products->getSize()){
	$selector    = 'magepow_specialpromotions-'.uniqid();
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
	$review = $block->getData('review');
	$showWishlist = $block->getData('wishlist');
    $showCompare = $block->getData('compare');
    $showCart = $block->getData('cart');
?>
    <div class="block widget block-new-products-list">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getBlockTitle())) ?></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $block->getNameInLayout(); ?>
            <div class="<?php echo $selector ?>" data-mage-init='{"gridSlider": {}}'>
            <?php 
            		echo '<ul class="slider grid-slider"
	                    data-slides-To-Show="8",
	                    data-vertical-Swiping="true",
	                    data-vertical="true",';
	                    foreach ($this->getFrontendCfg() as $opt){
	                    	if($opt=='vertical'||$opt=='fade')continue;
	                        if($opt!="slide" && $opt !='responsive') echo 'data-'.$opt.'= '.$this->getData($opt).' ';
	                        if($opt=='responsive')echo 'data-'.$opt."= '".$this->getData($opt)."'";
	                    }
	                echo '>';
            ?>
                <?php foreach ($_products->getItems() as $_product) :?>
                    <!-- <div class="product-item"> -->
                    <li class="product-item">
                        <div class="product-item-info">
                            <a class="product-item-photo" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                               title="<?= /* @noEscape */ $block->stripTags($_product->getName(), null, true) ?>">
                               <img src=<?= 
                                    $block->_imageHelper->init($_product, 'side_column_widget_product_thumbnail')->constrainOnly(TRUE)
                                               ->keepAspectRatio(TRUE)
                                               ->keepTransparency(TRUE)
                                               ->keepFrame(FALSE)
                                               ->resize($this->getData('widthImages'), $this->getData('heightImages'))->getUrl();
                                    ?>
                                >
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $block->stripTags($_product->getName(), null, true) ?>)"
                                       class="product-item-link">
                                        <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= $block->getProductPriceHtml($_product, '-widget-new-' . $suffix) ?>
                                <?php if ($templateType && $review) :?>
                                    <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?php endif; ?>
                                <?php if ($showWishlist || $showCompare || $showCart) :?>
                                    <div class="product-item">
                                    <div class="product-item-actions">
                                        <?php if ($showCart) :?>
                                            <div class="actions-primary">
                                                <?php if ($_product->isSaleable()) :?>
                                                    <?php if (!$_product->getTypeInstance()->isPossibleBuyFromList($_product)) :?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_product)) ?>"}}'
                                                                type="button"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else :?>
                                                        <?php
                                                            $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                                            $postData = $postDataHelper->getPostData(
                                                                $block->escapeUrl($block->getAddToCartUrl($_product)),
                                                                ['product' => (int) $_product->getEntityId()]
                                                            )
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= /* @noEscape */ $postData ?>'
                                                                type="button"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else :?>
                                                    <?php if ($_product->getIsSalable()) :?>
                                                        <div class="stock available">
                                                            <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                        </div>
                                                    <?php else :?>
                                                        <div class="stock unavailable">
                                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare) :?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) :?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>'
                                                       class="action towishlist"
                                                       data-action="add-to-wishlist"
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare) :?>
                                                    <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_product) ?>'
                                                       title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </li>
                    <!-- </div> -->
                <?php endforeach; ?>
            </ul>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php } ?>
